//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace collegemanagementASP.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class newadmission
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter student name.")]
        
        public string fname { get; set; }

        [Required(ErrorMessage = "Please enter student Guardian name.")]
        public string gname { get; set; }

        [Required(ErrorMessage = "Please enter Gender.")]
        public string gender { get; set; }

        [Required(ErrorMessage = "Please enter student Date of Birth.")]
        public string dob { get; set; }

        [Required(ErrorMessage = "Please enter student Mobile number.")]
        public string mobile { get; set; }

        [Required(ErrorMessage = "Please enter student Email.")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Required(ErrorMessage = "Please enter student Semester.")]
        public string semster { get; set; }

        [Required(ErrorMessage = "Please enter student Program.")]
        public string prog { get; set; }

        [Required(ErrorMessage = "Please enter student School name.")]
        public string sname { get; set; }

        [Required(ErrorMessage = "Please enter student batch duration.")]
        public string duration { get; set; }

        [Required(ErrorMessage = "Please enter student Address.")]
        public string address { get; set; }

        public int status { get; set; }
    }
}
